rania:
    resource: "@RaniaBundle/Resources/config/routing.yml"
    prefix:   /web

auto_ecole:
    resource: "@AutoEcoleBundle/Resources/config/routing.yml"
    prefix:   /ws

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"