<?php

namespace AutoEcoleBundle\Repository;

/**
 * AnnulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnulationRepository extends \Doctrine\ORM\EntityRepository
{
}
