<?php

namespace AutoEcoleBundle\Repository;

/**
 * MoniteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoniteurRepository extends \Doctrine\ORM\EntityRepository
{
}
